#!/usr/bin/env bash
#
# Environmental variables used by the experimental protocols.
#       Source this file in .bashrc to have the variables available.
#

export prot_setup="HEKA-EPC10"
#export prot_setup="AXON-700B"

prot_set_lcg_var() {
    tmp=(`prot_return_lcg_cfg $1 $2`)
## Sets lcg enviromental variables given the headstage and the protocol. 
    export AI_CHANNEL=${tmp[0]}
	export AO_CHANNEL=${tmp[1]}
	export AI_CONVERSION_FACTOR=${tmp[2]}
	export AO_CONVERSION_FACTOR=${tmp[3]}
	export INPUT_UNITS=${tmp[4]}
	export OUTPUT_UNITS=${tmp[5]}
}
export -f prot_export_lcg_var
# Default parameters for the protocols
export prot_kernel="yes"
export prot_prot="yes"
export prot_figures="yes"
export prot_kernel_sd=150
export prot_srate=30000

# Path to the prot folder
export PROTDIR=$HOME/lib/prot
export setups_cfg=$PROTDIR/setups.cfg
# Path to the matlab library 
# git clone https://github.com/jcouto/matlab.git
export MATLABLIBDIR=$HOME/lib/matlab

export PATH=$PATH:$PROTDIR/scripts
