#! /usr/bin/env bash
#
# Protocol to inject noise and to characterize the dynamic IV curves.
#
amp=200,0
sd="75,75"
tau="3,10"
dur=40
T=1
n=3
i=10
kernel=$prot_kernel
prot=$prot_prot
figures=$prot_figures
headstage=0

usage="EIF protocol. Injects current noise in cell \n
to charactherize the dynamic IV curve. Sums 2 waveforms...\n
    Usage : `basename $0` [options <value>]\n
\n
    Options:\n
        \t-a amplitude		      Amplitude of the noise.\n
        \t   ($amp pA)				.\n
        \t-s standard deviation   Standard deviation of the noise.\n
        \t   ($sd pA )			  Percentage of the amplitude (if bellow zero).\n
        \t-T time constant		  Time constant of the noise.\n
        \t   ($tau ms)       Specify the start, stop and step values.\n
        \t-d duration             Duration of the step.\n
        \t  ($dur sec)\n         
        \t-t tail                 Duration before and after the step.\n
        \t  ($T sec)\n
        \t-i interval             Interval to wait between trials.\n
        \t  ($i sec)\n
        \t-n repetitions          Number of repetitions of each trial.\n
        \t  ($n)\n
        \t-H headstage            Headstage to use.\n
        \t  ($headstage)\n
        \t-h,--help               Display this help message and quit.\n
        \t--(no-)kernel			  (Does not) compute the kernel\n
        \t--(no-)prot             (Does not) run the steps\n
        \t--(no-)figures          (Does not) analyze the data\n
    
    Examples:\n
        \tRun 800ms long steps from -500 to 1500 pA with 100pA intervals on headstage 2 \n
        \t\t  prot-steps -a -500,1500,100 -n 1 -d 0.8 -H 2\n

"
if ! options=$(getopt -o ha:d:T:s:t:i:n:H: --long no-kernel,kernel,no-prot,prot,no-figures,figures -- "$@")
then
    echo -e $usage
    exit 1
fi

eval set -- "$options"

while [ $# -gt 0 ]
do
    case $1 in
    -h) echo -e $usage
        exit 0 ;;
    --no-kernel) kernel="no" ;;
    --kernel) kernel="yes" ;;
    --no-prot) prot="no" ;;
    --prot) prot="yes" ;;
    --no-figures) figures="no" ;;
    --figures) figures="yes" ;;
    # for options with required arguments, an additional shift is required
    -a) amp=$2 ; shift;;
    -d) dur=$2 ; shift;;
    -t) T=$2 ; shift;;
    -s) sd=$2 ; shift;;
    -T) tau=$2 ; shift;;
    -i) i=$2 ; shift;;
    -n) n=$2 ; shift;;
    -H) headstage=$2 ; shift;;
    --) shift; break;;
    -*) echo "$0: error - unrecognized option $1" 1>&2; exit 1;;
    *) break;;
    esac
    shift
done

prot_set_headstage $headstage "cc"

if [ $kernel == "yes" ] ; then
	lcg-kernel -s $prot_kernel_sd -I $AI_CHANNEL -O $AO_CHANNEL -F $prot_srate
fi

if [ $prot == "yes" ] ; then
	
	lcg-ou -m $amp -s $sd -t $tau -d $dur -D $T \
        -i $i -n $n -F $prot_srate --no-kernel
fi

if [ $figures == "yes" ] ; then
    matlab -nodesktop -nosplash < $PROTDIR/matlab/analize_eif_protocol.m
fi
