#! /usr/bin/env bash
#
# Protocol to inject short pulses to characterize the membrane time constant.
#
amp=-300
dur=60
n=1
i=1
pw=1000
T=1
freq=0.5
kernel=$prot_kernel
prot=$prot_prot
figures=$prot_figures
headstage="0,1"
offset=0

usage="Dual cell pulses protocol. Injects current pulses in a cell \n
to charactherize its time constant.\n
    Usage : `basename $0` [options <value>]\n
\n
    Options:\n
        \t-a amplitude		      Amplitude of the steps.\n
        \t   ($amp pA)       \n
        \t-d duration             Duration of the pulse (ms).\n
        \t  ($dur ms)\n         
        \t-i interval             Interval to wait between trials.\n
        \t  ($i sec)\n
        \t-n repetitions          Number of repetitions of each trial.\n
        \t  ($n)\n
        \t-H headstage            Headstage to use.\n
        \t  ($headstage)\n
        \t-h,--help               Display this help message and quit.\n
        \t--(no-)kernel			  (Does not) compute the kernel\n
        \t--(no-)prot             (Does not) run the steps\n
        \t--(no-)figures          (Does not) analyze the data\n
    
    Examples:\n
        \tRun 10ms short pulses with -300 pA on headstage 2 \n
        \t\t  prot-tau -a --300 -n 1 -d 10 -H 2\n

"
if ! options=$(getopt -o ha:f:p:d:i:n:H: --long no-kernel,kernel,no-prot,prot,no-figures,figures -- "$@")
then
    echo -e $usage
    exit 1
fi

eval set -- "$options"

while [ $# -gt 0 ]
do
    case $1 in
    -h) echo -e $usage
        exit 0 ;;
    --no-kernel) kernel="no" ;;
    --kernel) kernel="yes" ;;
    --no-prot) prot="no" ;;
    --prot) prot="yes" ;;
    --no-figures) figures="no" ;;
    --figures) figures="yes" ;;
    # for options with required arguments, an additional shift is required
    -a) amp=$2 ; shift;;
    -d) dur=$2 ; shift;;
    -p) pw=$2 ; shift;;
    -f) freq=$2 ; shift;;
    -i) i=$2 ; shift;;
    -n) n=$2 ; shift;;
    -H) headstage=$2 ; shift;;
    --) shift; break;;
    -*) echo "$0: error - unrecognized option $1" 1>&2; exit 1;;
    *) break;;
    esac
    shift
done

SAVE_IFS=$IFS
IFS=','
j=0
order=(cc vc)
for i in $headstage
do
        prot_set_headstage $i ${order[$j]}
        ai[$j]=$AI_CHANNEL
        ao[$j]=$AO_CHANNEL
        aiunits[$j]=$INPUT_UNITS
        aounits[$j]=$OUTPUT_UNITS
        aifactors[$j]=$AI_CONVERSION_FACTOR
        aofactors[$j]=$AO_CONVERSION_FACTOR
    ((j++))
done
if [ $kernel == "yes" ] ; then
    kernel=""
else
    kernel="--no-kernel"
fi
    echo "lcg-stimgen poisson-reg --P1 $amp --P2 $freq --P3 $pw -d $dur -t $T -i $i -n $n -F $prot_srate $kernel -I ${ai[*]} -O ${ao[0]}  --Iu ${aiunits[*]} --Ou ${aounits[0]} --If ${aifactors[*]} --Of ${aofactors[0]} -o $offset --Ks $prot_kernel_sd" 
    eval "lcg-stimgen poisson-reg --P1 $amp --P2 $freq --P3 $pw -d $dur -t $T -i $i -n $n -F $prot_srate $kernel -I ${ai[*]} -O ${ao[0]}  --Iu ${aiunits[*]} --Ou ${aounits[0]} --If ${aifactors[*]} --Of ${aofactors[0]} -o $offset --Ks $prot_kernel_sd" 
IFS=$SAVE_IFS
